name: Update letsblock.it blocklist

on:
  push:
    paths:
      - letsblockit-blocklist.yaml
      - .github/workflows/letsblockit-render.yaml
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.9'
      - name: Generate blocklist
        run: |-
          set -euo pipefail
          go run github.com/letsblockit/letsblockit/cmd/render@latest --strict letsblockit-blocklist.yaml > letsblockit-blocklist.txt
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add letsblockit-blocklist.txt
          timestamp=$(date -u)
          # If nothing changed, we stop at the next line
          git commit -m "Updated letsblock.it blocklist: ${timestamp}" || exit 0
          git push
